### ISSUE TITLE
getNearest fails silently when dimensionality of ANNIndex doesn't match dimensionality of loaded tree object

### ISSUE THREAD

**Issue by flylo** [spotify/annoy-java#7]
If I make a tree in python with dimensionality 10, like so:
```python
from annoy import AnnoyIndex
import random

f = 10  # specifying dimensionality 10
t = AnnoyIndex(f)
for i in range(1000):
    v = [random.gauss(0, 1) for z in range(f)]
    t.add_item(i, v)

t.build(5)
t.save('/Users/ZacP/test.ann')
```
And then try to load that tree in a scio job, run in the REPL using `sbt repl/run`:

```scala
import com.spotify.scio.values.DistCache
import org.joda.time.format.DateTimeFormat
import scala.collection.JavaConversions._
import com.spotify.annoy.{ANNIndex, AnnoyIndex}

val annTree: DistCache[AnnoyIndex] = sc.distCache {
      "/Users/ZacP/test.ann"
    } { f => new ANNIndex(11, f.getPath) }  // the "11" here specifies a dimensionality that is greater than what the tree actually has

val myCollection = 0 until 10

myCollection.flatMap {
  r =>
    val tree = annTree()
    tree.getNearest(List.fill(10)(0.0).map(_.toFloat).toArray, 10).toList
}
```
The result of the `flatMap()` stored in `output` is just an empty vector. If we make a new `ANNIndex` with dimensionality _less_ than what the underlying tree actually has, then it throws an `IndexOutOfBoundsException`. This is inconsistent behavior. I propose that there should be an error message telling the user that the dimensionality of the ANNIndex doesn't match that of the query vector, regardless of whether the query vector is shorter or longer than expected.

**Comment by erikbern** [comment]
the dimensionality isn't stored in the file anywhere, so that would be hard to fix

you could potentially check that the size of the file is an even multiple of the size of a single vector, but that's not 100% foolproof

**Comment by a1k0n** [comment]
Yes, it's unfortunate that there's no header. But I think @flylo is suggesting simply throwing an exception if the length of the vector passed to `getNearest` doesn't match the dimensionality passed to the AnnoyIndex constructor, which would maybe help catch some of these errors.

**Comment by erikbern** [comment]
yeah that's true. i think the python interface does that

**Comment by flylo** [comment]
yeah, that's exactly what i was suggesting @a1k0n

**Comment by a1k0n** [comment]
send a pull request! I don't think either Erik or I are actively working on annoy at the moment...

**Comment by yonromai** [comment]
@flylo we're slowly deprecating this annoy-java for a faster and more up to date version based on JNI: https://github.com/yonromai/annoy-java
The plan is to test it further in production (inferno is currently using the new version in prod), then move this one to the graveyard and move the jni one from my repo to Spotify's. 
Mind giving it a try?
